### ISSUE TITLE
My code causes panic

### ISSUE THREAD

**Issue by fallais** [dop251/goja#127]
Hello,

I am using code that cause this panic (sorry I need to *xxxxxxxx* some values).

```txt
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0xc2b677]

goroutine 1800 [running]:
github.com/dop251/goja.AssertFunction.func1.1(0xc00021fe18)
        D:/Dev/src/github.com/dop251/goja/runtime.go:1485 +0x9f
panic(0xf41ee0, 0x1b4d830)
        c:/go/src/runtime/panic.go:679 +0x1c0
github.com/dop251/goja.(*vm).try.func1(0xc0002d55f0, 0x0, 0xc00021fce8, 0x0, 0x0, 0x0, 0xc00021fd40)
        D:/Dev/src/github.com/dop251/goja/vm.go:377 +0x3b7
panic(0xf41ee0, 0x1b4d830)
        c:/go/src/runtime/panic.go:679 +0x1c0
github.com/dop251/goja.(*vm).run(0xc0002d55f0)
        D:/Dev/src/github.com/dop251/goja/vm.go:289 +0x67
github.com/dop251/goja.(*funcObject).Call(0xc0002f6300, 0x0, 0x0, 0xc000836fa0, 0x2, 0x2, 0x1e206b0, 0x0)
        D:/Dev/src/github.com/dop251/goja/func.go:130 +0x2d3
github.com/dop251/goja.AssertFunction.func1.2()
        D:/Dev/src/github.com/dop251/goja/runtime.go:1490 +0x9d
github.com/dop251/goja.(*vm).try(0xc0002d55f0, 0xc00021fd90, 0x0)
        D:/Dev/src/github.com/dop251/goja/vm.go:383 +0x14e
github.com/dop251/goja.AssertFunction.func1(0x0, 0x0, 0xc000836fa0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
        D:/Dev/src/github.com/dop251/goja/runtime.go:1489 +0x141
xxxx/internal/components/collector/normalizers/javascript.(*jsNormalizer).exclude(0xc00039e160, 0xc000252b60, 0xc0002c43a7, 0x5, 0x0, 0xed5df5f4f, 0x1b6e720)
        D:/Dev/src/xxxxx/internal/components/collector/normalizers/javascript/exclude.go:33 +0x469
xxxxxx/internal/components/collector/normalizers/javascript.(*jsNormalizer).Normalize.func1(0xc000450900, 0xc0004508a0, 0x12b1260, 0xc000269bc0, 0xc00039e160, 0xc000926600)
        D:/Dev/src/xxxxxx/internal/components/collector/normalizers/javascript/javascript.go:67 +0x12e
created by xxxxx/internal/components/collector/normalizers/javascript.(*jsNormalizer).Normalize
        D:/Dev/src/xxxxxxx/internal/components/collector/normalizers/javascript/javascript.go:55 +0x95
exit status 2
```

I am using kind of **stages** that perform normalization, for example :

```golang
func (norm *jsNormalizer) exclude(incident *models.Incident, slug string) (bool, error) {
	// Marshal incident as JSON object
	incidentJSON, err := json.Marshal(incident)
	if err != nil {
		return false, fmt.Errorf("Error while marshalling the incident : %s", err)
	}

	// Create the VM
	vm := goja.New()

	// Run the script
	_, err = vm.RunString(norm.script)
	if err != nil {
		return false, fmt.Errorf("Error while running the JS code: %s", err)
	}

	// Run
	excludeFunc, ok := goja.AssertFunction(norm.vm.Get("Exclude"))
	if !ok {
		return false, fmt.Errorf("Error while asserting the function [Exclude]: %s", err)
	}
	returnRaw, err := excludeFunc(nil, vm.ToValue(string(incidentJSON)), vm.ToValue(slug))
	if err != nil {
		return false, fmt.Errorf("Error while executing the function [Exclude]: %s", err)
	}

	excluded := returnRaw.ToBoolean()

	return excluded, nil
}
```

Part of the big picture below.

```golang
go func() {
		defer close(normalizedIncidentsCh)

		for incident := range incidents {
			// Stop if the context is done
			select {
			case <-ctx.Done():
				return
			default:
			}

			// Exclude
			exclude, err := norm.exclude(incident, customer.Slug)
			if err != nil {
				logrus.WithError(err).Errorln("Error while setting the variables")
			}
			if exclude {
				continue
			}

			// Copy
			normalizedIncident := incident

			// Status
			status, err := norm.calculateStatus(incident, customer.Slug)
			if err != nil {
				logrus.WithError(err).Errorln("Error while calculating the status")
			}
			normalizedIncident.Status = status

			// Criticity
			criticity, err := norm.calculateCriticity(incident, customer.Slug)
			if err != nil {
				logrus.WithError(err).Errorln("Error while calculating the criticity")
			}
			normalizedIncident.Criticity = criticity

			// Append
			normalizedIncidentsCh <- normalizedIncident
		}
	}()
```

**Comment by dop251** [comment]
You may have hit a bug in the compiler but I can't tell you more without a reproducible test case that I could run myself. Could you provide it please?

**Comment by fallais** [comment]
Hello, what could I show you more ? I can't show you the exact content of the JS code and I will need to obfuscate some of the core code.. :(

I could investigate if you tell me what your opinion on this is, based on the lines mentionned on the stacktrace maybe ? Could it be because of goroutines ? I use them but I am pretty sure that the VM is not called by multiple goroutines, only one.

**Comment by dop251** [comment]
The problem is triggered by the javascript code (unless it's a concurrency issue, but like you said it's unlikely). Can you reproduce it reliably? If so try to isolate it by removing parts of the javascript code until you find the part that causes the failure. Then create a test case with just that part (obfuscate it if necessary).

**Comment by fallais** [comment]
It is totally random.. Basically, I am scrapping a REST API and processing all the objects that I receive into a normalization pipeline. I try to remove parts of the JS code until the function is basic that it onlr return *false* for example, and it still panic. So I think the JS code is not responsible. It is always the `Exclude` function that seems to trigger the panic.

Panic message is also changing.

```txt
panic: runtime error: index out of range [-2] [recovered]
        panic: runtime error: index out of range [-2] [recovered]
        panic: runtime error: index out of range [-2]

goroutine 633 [running]:
github.com/dop251/goja.AssertFunction.func1.1(0xc000539e18)
        D:/Dev/src/github.com/dop251/goja/runtime.go:1485 +0x9f
panic(0xfeb780, 0xc00023d420)
        c:/go/src/runtime/panic.go:679 +0x1c0
github.com/dop251/goja.(*vm).try.func1(0xc0002e95f0, 0x1, 0xc000539ce8, 0x4, 0x0, 0x0, 0xc000539d40)
        D:/Dev/src/github.com/dop251/goja/vm.go:377 +0x3b7
panic(0xfeb780, 0xc00023d420)
        c:/go/src/runtime/panic.go:679 +0x1c0
github.com/dop251/goja.loadStack.exec(0xffffffffffffffff, 0xc0002e95f0)
        D:/Dev/src/github.com/dop251/goja/vm.go:550 +0x670
github.com/dop251/goja.(*vm).run(0xc0002e95f0)
        D:/Dev/src/github.com/dop251/goja/vm.go:289 +0xa0
github.com/dop251/goja.(*funcObject).Call(0xc000328300, 0x0, 0x0, 0xc0007b0560, 0x2, 0x2, 0x1e20008, 0x0)
        D:/Dev/src/github.com/dop251/goja/func.go:130 +0x2d3
github.com/dop251/goja.AssertFunction.func1.2()
        D:/Dev/src/github.com/dop251/goja/runtime.go:1490 +0x9d
github.com/dop251/goja.(*vm).try(0xc0002e95f0, 0xc000539d90, 0x0)
        D:/Dev/src/github.com/dop251/goja/vm.go:383 +0x14e
github.com/dop251/goja.AssertFunction.func1(0x0, 0x0, 0xc0007b0560, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0)
        D:/Dev/src/github.com/dop251/goja/runtime.go:1489 +0x141

...
...
...
```

**Comment by fallais** [comment]
Always this part.

```golang
        // Run
	excludeFunc, ok := goja.AssertFunction(norm.vm.Get("Exclude"))
	if !ok {
		return false, fmt.Errorf("Error while asserting the function [Exclude]: %s", err)
	}
	returnRaw, err := excludeFunc(nil, vm.ToValue(string(incidentJSON)), vm.ToValue(slug))
	if err != nil {
		return false, fmt.Errorf("Error while executing the function [Exclude]: %s", err)
	}
```

This : 

```golang
returnRaw, err := excludeFunc(nil, vm.ToValue(string(incidentJSON)), vm.ToValue(slug))
```

how could this panic with the `ok` checking right above ?

**Comment by fallais** [comment]
Ok... my bad... This part was remaining : `goja.AssertFunction(norm.vm.Get("Exclude"))`

I was using the `vm` property of the class, here the `norm.vm`. Did not see it.

Originally, I was reusing the VM for performance purposes (with Otto).

**Comment by fallais** [comment]
That leads me to a question for you, it is OK regarding performances to instantiate a GOJA VM at each stage of my pipeline ? It seems bad to me.. :(

**Comment by dop251** [comment]
You should definitely reuse the vm. Create a vm, then run the code that defines the Exclude function, then use this vm multiple times. You will get a massive performance boost by doing so. You just need to make sure that any vm is only used by one goroutine at a time. A natural way of doing it would be to associate a vm with each worker goroutine. If this is tricky you can use sync.Pool.
