### ISSUE TITLE
panic: Invalid regular expression (regexp2): 0:(?)

### ISSUE THREAD

**Issue by MStoykov** [dop251/goja#216]
Again through fuzzing, the code to reproduce is `"\xbd000".split(/0:(?)/g)` 

```
panic: Invalid regular expression (regexp2): 0:(?) (error parsing regexp: missing argument to repetition operator in `0:(?)`) [recovered]
        panic: Invalid regular expression (regexp2): 0:(?) (error parsing regexp: missing argument to repetition operator in `0:(?)`)

goroutine 18 [running]:
testing.tRunner.func1.1(0x7e5da0, 0xc00016a6e0)
        testing/testing.go:988 +0x30d
testing.tRunner.func1(0xc0000dc360)
        testing/testing.go:991 +0x3f9
panic(0x7e5da0, 0xc00016a6e0)
        runtime/panic.go:969 +0x166
github.com/dop251/goja.(*regexpPattern).createRegexp2(0xc00009b1d0)
        github.com/dop251/goja/regexp.go:91 +0xb7
github.com/dop251/goja.(*regexpPattern).findAllSubmatchIndex(0xc00009b1d0, 0x91e420, 0xc000158780, 0x0, 0xffffffffffffffff, 0x0, 0xc0001578c0, 0xc00014f590, 0xc0000b3200)
        github.com/dop251/goja/regexp.go:164 +0x23e
github.com/dop251/goja.(*Runtime).regexpproto_stdSplitter(0xc000120580, 0x91c620, 0xc0001578c0, 0xc000158760, 0x2, 0x2, 0x91c601, 0xc000158760)
        github.com/dop251/goja/builtin_regexp.go:889 +0x4fa
github.com/dop251/goja.(*Runtime).stringproto_split(0xc000120580, 0x91c9e0, 0xc0000bcb60, 0xc000107160, 0x1, 0x4, 0xc0000ea910, 0x120)
        github.com/dop251/goja/builtin_string.go:725 +0x6c1
github.com/dop251/goja.(*vm)._nativeCall(0xc000140000, 0xc00014a840, 0x1)
        github.com/dop251/goja/vm.go:1818 +0x2d7
github.com/dop251/goja.call.exec(0xc000000001, 0xc000140000)
        github.com/dop251/goja/vm.go:1790 +0xb8f
github.com/dop251/goja.(*vm).run(0xc000140000)
        github.com/dop251/goja/vm.go:307 +0x9d
```

**Comment by MStoykov** [comment]
Other ones in no particular order, but only with the regexp (I don't think the string against which it's matched is relevant):
```
	panic: Invalid regular expression (regexp2): (?U) (error parsing regexp: unrecognized grouping construct: (?U in `(?U)`)
	panic: Invalid regular expression (regexp2): (?) (error parsing regexp: missing argument to repetition operator in `(?)`)
	panic: Invalid regular expression (regexp2): (?)|(?i) (error parsing regexp: missing argument to repetition operator in `(?)|(?i)`)
	panic: Invalid regular expression (regexp2): (?)0(?i) (error parsing regexp: missing argument to repetition operator in `(?)0(?i)`)
	panic: Invalid regular expression (regexp2): (?)0(0i) (error parsing regexp: missing argument to repetition operator in `(?)0(0i)`)
	panic: Invalid regular expression (regexp2): (?)0(00) (error parsing regexp: missing argument to repetition operator in `(?)0(00)`)
	panic: Invalid regular expression (regexp2): (?)0(0) (error parsing regexp: missing argument to repetition operator in `(?)0(0)`)
	panic: Invalid regular expression (regexp2): (?)0() (error parsing regexp: missing argument to repetition operator in `(?)0()`)
	panic: Invalid regular expression (regexp2): (?)(0) (error parsing regexp: missing argument to repetition operator in `(?)(0)`)
	panic: Invalid regular expression (regexp2): (?)() (error parsing regexp: missing argument to repetition operator in `(?)()`)
	panic: Invalid regular expression (regexp2): (?)(00) (error parsing regexp: missing argument to repetition operator in `(?)(00)`)
	panic: Invalid regular expression (regexp2): ^:0(?) (error parsing regexp: missing argument to repetition operator in `^:0(?)`)
	panic: Invalid regular expression (regexp2): ^:?(?) (error parsing regexp: missing argument to repetition operator in `^:?(?)`)
	panic: Invalid regular expression (regexp2): (?)(?) (error parsing regexp: missing argument to repetition operator in `(?)(?)`)
	panic: Invalid regular expression (regexp2): ^00(?) (error parsing regexp: missing argument to repetition operator in `^00(?)`)
	panic: Invalid regular expression (regexp2): (?)0(i) (error parsing regexp: missing argument to repetition operator in `(?)0(i)`)
	panic: Invalid regular expression (regexp2): (0)(?) (error parsing regexp: missing argument to repetition operator in `(0)(?)`)
	panic: Invalid regular expression (regexp2): 0(?) (error parsing regexp: missing argument to repetition operator in `0(?)`)
	panic: Invalid regular expression (regexp2): 000(?) (error parsing regexp: missing argument to repetition operator in `000(?)`)
	panic: Invalid regular expression (regexp2): (?)(i) (error parsing regexp: missing argument to repetition operator in `(?)(i)`)
	panic: Invalid regular expression (regexp2): 00(?) (error parsing regexp: missing argument to repetition operator in `00(?)`)
	panic: Invalid regular expression (regexp2): (?P<w>)(?P<w>)(?P<D>) (error parsing regexp: unrecognized grouping construct: (?P in `(?P<w>)(?P<w>)(?P<D>)`)
	panic: Invalid regular expression (regexp2): (?)(0i) (error parsing regexp: missing argument to repetition operator in `(?)(0i)`)
	panic: Invalid regular expression (regexp2): ^(?) (error parsing regexp: missing argument to repetition operator in `^(?)`)
	panic: Invalid regular expression (regexp2): ()(?) (error parsing regexp: missing argument to repetition operator in `()(?)`)
	panic: Invalid regular expression (regexp2): (?)0(?) (error parsing regexp: missing argument to repetition operator in `(?)0(?)`)
	panic: Invalid regular expression (regexp2): (0)0(?) (error parsing regexp: missing argument to repetition operator in `(0)0(?)`)
	panic: Invalid regular expression (regexp2): ()0(?) (error parsing regexp: missing argument to repetition operator in `()0(?)`)
	panic: Invalid regular expression (regexp2): (?)(?i) (error parsing regexp: missing argument to repetition operator in `(?)(?i)`)
	panic: Invalid regular expression (regexp2): (?)|(?) (error parsing regexp: missing argument to repetition operator in `(?)|(?)`)
	panic: Invalid regular expression (regexp2): (?P<w>)(?P<w>)(?P<0>) (error parsing regexp: unrecognized grouping construct: (?P in `(?P<w>)(?P<w>)(?P<0>)`)
	panic: Invalid regular expression (regexp2): (0)|(?) (error parsing regexp: missing argument to repetition operator in `(0)|(?)`)
	panic: Invalid regular expression (regexp2): |(?) (error parsing regexp: missing argument to repetition operator in `|(?)`)
	panic: Invalid regular expression (regexp2): ()|(?) (error parsing regexp: missing argument to repetition operator in `()|(?)`)
	panic: Invalid regular expression (regexp2): (?)(?)|(?i) (error parsing regexp: missing argument to repetition operator in `(?)(?)|(?i)`)
	panic: Invalid regular expression (regexp2): 0|(?) (error parsing regexp: missing argument to repetition operator in `0|(?)`)
	panic: Invalid regular expression (regexp2): (?)(?)0(?i) (error parsing regexp: missing argument to repetition operator in `(?)(?)0(?i)`)
	panic: Invalid regular expression (regexp2): (?P<w>)(?P<w>)(0P<0>) (error parsing regexp: unrecognized grouping construct: (?P in `(?P<w>)(?P<w>)(0P<0>)`)
	panic: Invalid regular expression (regexp2): (?)(?)0(0i) (error parsing regexp: missing argument to repetition operator in `(?)(?)0(0i)`)
	panic: Invalid regular expression (regexp2): 0^(?) (error parsing regexp: missing argument to repetition operator in `0^(?)`)
	panic: Invalid regular expression (regexp2): (?)(?)0(00) (error parsing regexp: missing argument to repetition operator in `(?)(?)0(00)`)
	panic: Invalid regular expression (regexp2): (?)(0)0(00) (error parsing regexp: missing argument to repetition operator in `(?)(0)0(00)`)
	panic: Invalid regular expression (regexp2): (?)(0)0(0) (error parsing regexp: missing argument to repetition operator in `(?)(0)0(0)`)
	panic: Invalid regular expression (regexp2): (?P<w>)(?P<w>)(0P<00) (error parsing regexp: unrecognized grouping construct: (?P in `(?P<w>)(?P<w>)(0P<00)`)
	panic: Invalid regular expression (regexp2): (?)(0)0() (error parsing regexp: missing argument to repetition operator in `(?)(0)0()`)
	panic: Invalid regular expression (regexp2): ^0(?) (error parsing regexp: missing argument to repetition operator in `^0(?)`)
	panic: Invalid regular expression (regexp2): (?)(0)(0) (error parsing regexp: missing argument to repetition operator in `(?)(0)(0)`)
	panic: Invalid regular expression (regexp2): (?)()() (error parsing regexp: missing argument to repetition operator in `(?)()()`)
	panic: Invalid regular expression (regexp2): (?)()0(0) (error parsing regexp: missing argument to repetition operator in `(?)()0(0)`)
	panic: Invalid regular expression (regexp2): (?)(0)() (error parsing regexp: missing argument to repetition operator in `(?)(0)()`)
	panic: Invalid regular expression (regexp2): (?P<w>)(?P<w>)(0P000) (error parsing regexp: unrecognized grouping construct: (?P in `(?P<w>)(?P<w>)(0P000)`)
	panic: Invalid regular expression (regexp2): (?)()(0) (error parsing regexp: missing argument to repetition operator in `(?)()(0)`)
	panic: Invalid regular expression (regexp2): 0:0(?) (error parsing regexp: missing argument to repetition operator in `0:0(?)`)
	panic: Invalid regular expression (regexp2): (?)()0() (error parsing regexp: missing argument to repetition operator in `(?)()0()`)
	panic: Invalid regular expression (regexp2): :0(?) (error parsing regexp: missing argument to repetition operator in `:0(?)`)
	panic: Invalid regular expression (regexp2): :(?) (error parsing regexp: missing argument to repetition operator in `:(?)`)
	panic: Invalid regular expression (regexp2): (?)(0)(00) (error parsing regexp: missing argument to repetition operator in `(?)(0)(00)`)
	panic: Invalid regular expression (regexp2): (?)()(00) (error parsing regexp: missing argument to repetition operator in `(?)()(00)`)
	panic: Invalid regular expression (regexp2): (?)(?)(?)(?)(?)(?)(?)(?)(?)(?)() (error parsing regexp: missing argument to repetition operator in `(?)(?)(?)(?)(?)(?)(?)(?)(?)(?)()`)
	panic: Invalid regular expression (regexp2): (?)()0(00) (error parsing regexp: missing argument to repetition operator in `(?)()0(00)`)
	panic: Invalid regular expression (regexp2): 0:(?) (error parsing regexp: missing argument to repetition operator in `0:(?)`)
	panic: Invalid regular expression (regexp2): (?P<w>)(?P<w>)(00000) (error parsing regexp: unrecognized grouping construct: (?P in `(?P<w>)(?P<w>)(00000)`)
	panic: Invalid regular expression (regexp2): (0)(?)0(00) (error parsing regexp: missing argument to repetition operator in `(0)(?)0(00)`)
	panic: Invalid regular expression (regexp2): (?)^^^^ (error parsing regexp: missing argument to repetition operator in `(?)^^^^`)
	panic: Invalid regular expression (regexp2): (0)(?)0(0) (error parsing regexp: missing argument to repetition operator in `(0)(?)0(0)`)
```

As you can see some of the errors are the same ... some aren't, but I decided not to make 20 issues of them
