### ISSUE TITLE
Problems with `Export`

### ISSUE THREAD

**Issue by MStoykov** [dop251/goja#270]
The following code:
```golang
package goja

import (
        "fmt"
        "testing"
)

func TestFrozenArrayExport(t *testing.T) {
        f := func(d interface{}) {
                switch a := d.(type) {
                case []interface{}:
                        for i, v := range a {
                                fmt.Printf("[%d]=%s\n", i, v)
                        }
                default:
                        panic("wat")
                }
        }

        vm := New()
        vm.Set("f", vm.ToValue(f))
        vm.RunString(`
                var s = [12,13,14];
                Object.freeze(s);
                f(s)
        `)
}
```
panics with 
```
--- FAIL: TestFrozenArrayExport (0.00s)
panic: Cannot export valueProperty [recovered]
        panic: Cannot export valueProperty [recovered]
        panic: Cannot export valueProperty [recovered]
        panic: Cannot export valueProperty

goroutine 34 [running]:
testing.tRunner.func1.2(0x7e1360, 0x911368)
        testing/testing.go:1144 +0x332
testing.tRunner.func1(0xc00011e300)
        testing/testing.go:1147 +0x4b6
panic(0x7e1360, 0x911368)
        runtime/panic.go:965 +0x1b9
github.com/dop251/goja.(*Runtime).RunProgram.func1(0xc000095ee8)
        github.com/dop251/goja/runtime.go:1206 +0x95
panic(0x7e1360, 0x911368)
        runtime/panic.go:965 +0x1b9
github.com/dop251/goja.(*vm).try.func1(0xc0001a0100, 0x0, 0xc000095d98, 0x0, 0x0, 0x0, 0xc000095e30)
        github.com/dop251/goja/vm.go:503 +0xc13
panic(0x7e1360, 0x911368)
        runtime/panic.go:965 +0x1b9
github.com/dop251/goja.(*valueProperty).Export(0xc0001d3920, 0x7eade0, 0x9274c8)
        github.com/dop251/goja/value.go:535 +0x39
github.com/dop251/goja.exportValue(0x9253a0, 0xc0001d3920, 0xc00011a078, 0x7dca80, 0xc00012c6d8)
        github.com/dop251/goja/value.go:1061 +0x88
github.com/dop251/goja.(*arrayObject).export(0xc0001d6540, 0xc00011a078, 0x7dca80, 0x7dca01)
        github.com/dop251/goja/array.go:491 +0x17c
github.com/dop251/goja.exportValue(0x9251d8, 0xc0001d38c0, 0xc00011a078, 0x926c01, 0x7efa40)
        github.com/dop251/goja/value.go:1059 +0x56
github.com/dop251/goja.(*Runtime).toReflectValue(0xc000125c00, 0x9251d8, 0xc0001d38c0, 0x7efa40, 0xc0001cecf0, 0x194, 0xc00011a078, 0x7f1d4b166a01, 0x925438)
        github.com/dop251/goja/runtime.go:1808 +0x293
github.com/dop251/goja.(*Runtime).wrapReflectFunc.func1(0x925860, 0xce26e0, 0xc000121620, 0x1, 0x2, 0x413b9d, 0x85d6ab)
        github.com/dop251/goja/runtime.go:1690 +0x2fa
github.com/dop251/goja.(*vm)._nativeCall(0xc0001a0100, 0xc0001d63c0, 0x1)
        github.com/dop251/goja/vm.go:2355 +0x266
github.com/dop251/goja.call.exec(0x1, 0xc0001a0100)
        github.com/dop251/goja/vm.go:2327 +0x776
github.com/dop251/goja.(*vm).run(0xc0001a0100)
        github.com/dop251/goja/vm.go:395 +0x94
github.com/dop251/goja.(*vm).try(0xc0001a0100, 0xc000095e98, 0x0)
        github.com/dop251/goja/vm.go:509 +0x188
github.com/dop251/goja.(*vm).runTry(...)
        github.com/dop251/goja/vm.go:514
github.com/dop251/goja.(*Runtime).RunProgram(0xc000125c00, 0xc0001790e0, 0x0, 0x0, 0x0, 0x0)
        github.com/dop251/goja/runtime.go:1221 +0x128
github.com/dop251/goja.(*Runtime).RunScript(0xc000125c00, 0x0, 0x0, 0x87336a, 0x33, 0x0, 0x0, 0x6058783d, 0x29f096b2)
        github.com/dop251/goja/runtime.go:1196 +0xb4
github.com/dop251/goja.(*Runtime).RunString(...)
        github.com/dop251/goja/runtime.go:1185
github.com/dop251/goja.TestFrozenArrayExport(0xc00011e300)
        github.com/dop251/goja/t_test.go:22 +0xd6
testing.tRunner(0xc00011e300, 0x8b93b0)
        testing/testing.go:1194 +0xef
created by testing.(*T).Run
        testing/testing.go:1239 +0x2b3
exit status 2
```
but:
1. Not freezing it 
2. changing the argument from `interface{}`  to `[]byte` or `[]int` , but not `[]interface{}`.
makes it work

**Comment by dzonerzy** [comment]
That acutally make sense imo, freeze make the object immutable and "not enumerable" thus goja runtime should be unable to export internal fields too, what's the expected behaviour in your opinion?
