### ISSUE TITLE
panic when executing Exception.String() or Exception.Error()

### ISSUE THREAD

**Issue by henkman** [dop251/goja#31]
following code panics:
```
package main

import (
	"fmt"
	"time"

	"github.com/dop251/goja"
)

func main() {
	vm := goja.New()
	time.AfterFunc(200*time.Millisecond, func() {
		vm.Interrupt("halt")
	})
	if v, err := vm.RunString(`i`); err == nil {
		fmt.Println(v.Export())
	} else {
		if _, ok := err.(*goja.InterruptedError); ok {
			fmt.Println("script took too long to execute")
		} else {
			fmt.Println(err.Error())
		}
	}
	fmt.Println("it's all over")
}
```

here is the stack trace:

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/dop251/goja.(*Program).sourceOffset(0x12765d10, 0x0, 0x1)
	path/src/github.com/dop251/goja/compiler.go:170 +0x4e
github.com/dop251/goja.(*stackFrame).position(0x127be260, 0x65623a, 0x0)
	path/src/github.com/dop251/goja/runtime.go:93 +0x2a
github.com/dop251/goja.(*stackFrame).write(0x127be260, 0x127bc9c0)
	path/src/github.com/dop251/goja/runtime.go:108 +0x78
github.com/dop251/goja.(*Exception).Error(0x127c0360, 0x6557f1, 0x1)
	path/src/github.com/dop251/goja/runtime.go:166 +0xc9
main.main()
	path/src/testme/main.go:21 +0x196
```

**Comment by henkman** [comment]
thanks!
