### ISSUE TITLE
Panic: index out of range

### ISSUE THREAD

**Issue by begmaroman** [dop251/goja#360]
effectiv-be_1              | panic: runtime error: index out of range [8] with length 8 [recovered]
effectiv-be_1              |    panic: runtime error: index out of range [8] with length 8 [recovered]
effectiv-be_1              |    panic: runtime error: index out of range [8] with length 8
effectiv-be_1              | 
effectiv-be_1              | goroutine 7855 [running]:
effectiv-be_1              | github.com/dop251/goja.AssertFunction.func1.1()
effectiv-be_1              |    /go/src/github.com/effectivai/effectiv-be/vendor/github.com/dop251/goja/runtime.go:2228 +0x74
effectiv-be_1              | panic({0x1696860, 0xc001122d80})
effectiv-be_1              |    /usr/local/go/src/runtime/panic.go:1038 +0x215
effectiv-be_1              | github.com/dop251/goja.(*vm).try.func1()
effectiv-be_1              |    /go/src/github.com/effectivai/effectiv-be/vendor/github.com/dop251/goja/vm.go:532 +0x529
effectiv-be_1              | panic({0x1696860, 0xc001122d80})
effectiv-be_1              |    /usr/local/go/src/runtime/panic.go:1038 +0x215
effectiv-be_1              | github.com/dop251/goja.(*vm).initStack(...)
effectiv-be_1              |    /go/src/github.com/effectivai/effectiv-be/vendor/github.com/dop251/goja/vm.go:798
effectiv-be_1              | github.com/dop251/goja.initStack.exec(...)
effectiv-be_1              |    /go/src/github.com/effectivai/effectiv-be/vendor/github.com/dop251/goja/vm.go:838
effectiv-be_1              | github.com/dop251/goja.(*vm).run(0xc000436a00)
effectiv-be_1              |    /go/src/github.com/effectivai/effectiv-be/vendor/github.com/dop251/goja/vm.go:410 +0x8b
effectiv-be_1              | github.com/dop251/goja.(*baseJsFuncObject)._call(0xc000b20340, {{0x1a1c0d0, 0x2777960}, {0xc006a22960, 0x5, 0x5}}, {0x0, 0x0}, {0x1a1b880, 0xc0005030e0})
effectiv-be_1              |    /go/src/github.com/effectivai/effectiv-be/vendor/github.com/dop251/goja/func.go:188 +0x2d8
effectiv-be_1              | github.com/dop251/goja.(*arrowFuncObject).Call(...)
effectiv-be_1              |    /go/src/github.com/effectivai/effectiv-be/vendor/github.com/dop251/goja/func.go:160
effectiv-be_1              | github.com/dop251/goja.AssertFunction.func1.2()
effectiv-be_1              |    /go/src/github.com/effectivai/effectiv-be/vendor/github.com/dop251/goja/runtime.go:2233 +0x7d
effectiv-be_1              | github.com/dop251/goja.(*vm).try(0x50, 0x7f5302a15f18)
effectiv-be_1              |    /go/src/github.com/effectivai/effectiv-be/vendor/github.com/dop251/goja/vm.go:538 +0x17d
effectiv-be_1              | github.com/dop251/goja.AssertFunction.func1({0x1a1c0d0, 0x2777960}, {0xc006a22960, 0xc0017d108b, 0x3})
effectiv-be_1              |    /go/src/github.com/effectivai/effectiv-be/vendor/github.com/dop251/goja/runtime.go:2232 +0x110

**Comment by dop251** [comment]
Hi. Unfortunately this stacktrace alone is not enough to diagnose the problem. Could you please try with the latest version of goja and if it still occurs provide a reproducible test case? Thanks.

**Comment by cyjme** [comment]
I got a similar panic. My solution is to add a Lock.

My panic code is here: 
```go
var vm *goja.Runtime

//create vm when init()
func init() {
	vm = goja.New()
	_, err := vm.RunString(`
              //jsFunc
       `)
}

//Run concurrently：

        jsFunc, ok := goja.AssertFunction(vm.Get("jsFunc"))
	if !ok {
		panic("Not a function")
	}
	res, err := compute(goja.Undefined(), vm.ToValue(param))

```

Solution:
```go
var vmLock sync.Mutex

//Run concurrently：

	vmLock.Lock()
        jsFunc, ok := goja.AssertFunction(vm.Get("jsFunc"))
	if !ok {
		panic("Not a function")
	}
	res, err := compute(goja.Undefined(), vm.ToValue(param))
	vmLock.Unlock()

```

**Comment by cyjme** [comment]
Append:

Oh,  I just saw this [https://github.com/dop251/goja#is-it-goroutine-safe](https://github.com/dop251/goja#is-it-goroutine-safe)

It's not goroutine-safe.

**Comment by testn** [comment]
Let's close this?
