### ISSUE TITLE
Panic in Export with String literals

### ISSUE THREAD

**Issue by MStoykov** [dop251/goja#366]
The following code
```golang
        f := func(v Value) {
                v.Export()
        }

        vm := New()
        vm.Set("f", f)
        vm.RunString("f`something`")
```
panics with 
```
panic: Cannot export valueProperty [recovered]
        panic: Cannot export valueProperty [recovered]
        panic: Cannot export valueProperty [recovered]
        panic: Cannot export valueProperty [recovered]
        panic: Cannot export valueProperty

goroutine 6 [running]:
testing.tRunner.func1.2({0x7cfac0, 0x8e7980})
        testing/testing.go:1209 +0x24e
testing.tRunner.func1()
        testing/testing.go:1212 +0x218
panic({0x7cfac0, 0x8e7980})
        runtime/panic.go:1038 +0x215
github.com/dop251/goja.(*Runtime).RunProgram.func1()
        github.com/dop251/goja/runtime.go:1357 +0x6e
panic({0x7cfac0, 0x8e7980})
        runtime/panic.go:1038 +0x215
github.com/dop251/goja.(*vm).try.func1()
        github.com/dop251/goja/vm.go:539 +0x635
panic({0x7cfac0, 0x8e7980})
        runtime/panic.go:1038 +0x215
github.com/dop251/goja.(*vm).try.func1()
        github.com/dop251/goja/vm.go:539 +0x635
panic({0x7cfac0, 0x8e7980})
        runtime/panic.go:1038 +0x215
github.com/dop251/goja.(*valueProperty).Export(0x902568)
        github.com/dop251/goja/value.go:535 +0x27
github.com/dop251/goja.exportValue({0x8fee40, 0xc0001ad170}, 0xc000164180)
        github.com/dop251/goja/value.go:1068 +0x4e
github.com/dop251/goja.(*arrayObject).export(0xc000164180, 0x1)
        github.com/dop251/goja/array.go:491 +0x1bc
github.com/dop251/goja.(*Object).Export.func1()
        github.com/dop251/goja/value.go:739 +0x4b
github.com/dop251/goja.(*vm).try(0x2, 0x2)
        github.com/dop251/goja/vm.go:547 +0x17d
github.com/dop251/goja.(*Runtime).tryPanic(...)
        github.com/dop251/goja/runtime.go:2353
github.com/dop251/goja.(*Object).Export(0x0)
        github.com/dop251/goja/value.go:738 +0x5d
github.com/dop251/goja.TestPanic.func1({0x8fec78, 0xc0001ad1d0})
        github.com/dop251/goja/p_test.go:7 +0x27
reflect.Value.call({0x7ce600, 0x889f50, 0x7fd039d07108}, {0x844c9a, 0x4}, {0xc00000c678, 0x1, 0xc0000619c8})
        reflect/value.go:543 +0x814
reflect.Value.Call({0x7ce600, 0x889f50, 0xc0001ad1d0}, {0xc00000c678, 0x1, 0x1})
        reflect/value.go:339 +0xc5
github.com/dop251/goja.(*Runtime).wrapReflectFunc.func1({{0x8ff300, 0xd3b6c0}, {0xc00001f4a0, 0x1, 0x2}})
        github.com/dop251/goja/runtime.go:1858 +0x259
github.com/dop251/goja.(*vm)._nativeCall(0xc000190000, 0xc0001a3860, 0x1)
        github.com/dop251/goja/vm.go:2725 +0x223
github.com/dop251/goja.call.exec(0x1, 0xc000190000)
        github.com/dop251/goja/vm.go:2697 +0x95b
github.com/dop251/goja.(*vm).run(0xc000190000)
        github.com/dop251/goja/vm.go:410 +0x8b
github.com/dop251/goja.(*vm).try(0x6d35ca, 0x0)
        github.com/dop251/goja/vm.go:547 +0x17d
```

While this might not be how template literal should be parsed/used it means that a panic can be provoked with any function that calls `Export` on its argument :(.

**Comment by dop251** [comment]
No, this is specific to tagged templates, going to fix shortly.

**Comment by MStoykov** [comment]
> No, this is specific to tagged templates, going to fix shortly. 

I somehow wrote "string literals" when I was wondering between "string templates" and "template literals" :facepalm: 

Thanks again for the really fast bug fixes :tada: :bow:
