### ISSUE TITLE
Panic on destructuring with rest

### ISSUE THREAD

**Issue by jmattheis** [dop251/goja#375]
Destructuring with rest parameter panics on an array that doesn't have enough properties. On nodejs & Firefox this seems to work without problems, `a` should be undefined and other an empty array.
```go
func main() {
	vm := goja.New()

	// works
	// _, err := vm.RunScript("test.js", `const [a, b] = [];`)
	// _, err := vm.RunScript("test.js", `const [a, ...other] = ['a'];`)

	// panics
	_, err := vm.RunScript("test.js", `const [a, ...other] = [];`)
	fmt.Println(err)
}
```
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x687259]

goroutine 1 [running]:
github.com/dop251/goja.(*Runtime).RunProgram.func1()
        /home/jm/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220214123719-b09a6bfa842f/runtime.go:1366 +0x6e
panic({0x7212a0, 0xb50430})
        /usr/lib/go/src/runtime/panic.go:838 +0x207
github.com/dop251/goja.(*vm).try.func1()
        /home/jm/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220214123719-b09a6bfa842f/vm.go:537 +0x635
panic({0x7212a0, 0xb50430})
        /usr/lib/go/src/runtime/panic.go:838 +0x207
github.com/dop251/goja.(*iteratorRecord).iterate(0xc0001a0a90, 0xc000083c98)
        /home/jm/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220214123719-b09a6bfa842f/runtime.go:2494 +0x39
github.com/dop251/goja._newArrayFromIter.exec({}, 0xc000182000)
        /home/jm/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220214123719-b09a6bfa842f/vm.go:1845 +0xf7
github.com/dop251/goja.(*vm).run(0xc000182000)
        /home/jm/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220214123719-b09a6bfa842f/vm.go:408 +0x8b
github.com/dop251/goja.(*vm).try(0x76fe5e?, 0x7?)
        /home/jm/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220214123719-b09a6bfa842f/vm.go:545 +0x176
github.com/dop251/goja.(*vm).runTry(...)
        /home/jm/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220214123719-b09a6bfa842f/vm.go:550
github.com/dop251/goja.(*Runtime).RunProgram(0xc0000ab880, 0x76fe5e?)
        /home/jm/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220214123719-b09a6bfa842f/runtime.go:1381 +0x19e
github.com/dop251/goja.(*Runtime).RunScript(0xc0000ab880?, {0x76fe5e?, 0x60?}, {0x77525d?, 0x0?})
        /home/jm/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220214123719-b09a6bfa842f/runtime.go:1356 +0x5a
main.main()
        /home/jm/src/test/main.go:17 +0x51
```

**Comment by dop251** [comment]
Thanks for reporting!

**Comment by jmattheis** [comment]
@dop251 Awesome, thanks for the fast fix.
