### ISSUE TITLE
Panic in `parser.ParseFile`

### ISSUE THREAD

**Issue by mrduncan** [dop251/goja#376]
This seemed to be the simplest case I could reproduce it with: https://go.dev/play/p/AKWKlcPqsrl

```go
package main

import "github.com/dop251/goja/parser"

func main() {
	parser.ParseFile(nil, "test.js", "var{..(", 0) // also reproducible with "const{..(" or "let{..("
}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4c351b]

goroutine 1 [running]:
github.com/dop251/goja/ast.(*PropertyKeyed).Idx0(0x28?)
	/tmp/gopath126714003/pkg/mod/github.com/dop251/goja@v0.0.0-20220324112439-a18ffb9c5866/ast/node.go:616 +0x1b
github.com/dop251/goja/parser.(*_parser).reinterpretAsObjectBindingPattern(0xc000136000?, 0xc00010e1e0)
	/tmp/gopath126714003/pkg/mod/github.com/dop251/goja@v0.0.0-20220324112439-a18ffb9c5866/parser/expression.go:1219 +0x45e
github.com/dop251/goja/parser.(*_parser).parseObjectBindingPattern(0x7fb3596bfa68?)
	/tmp/gopath126714003/pkg/mod/github.com/dop251/goja@v0.0.0-20220324112439-a18ffb9c5866/parser/expression.go:1180 +0x2b
github.com/dop251/goja/parser.(*_parser).parseBindingTarget(0xc00009ac08?)
	/tmp/gopath126714003/pkg/mod/github.com/dop251/goja@v0.0.0-20220324112439-a18ffb9c5866/parser/expression.go:228 +0x148
github.com/dop251/goja/parser.(*_parser).parseVariableDeclaration(0xc000136000, 0xc00009ac20)
	/tmp/gopath126714003/pkg/mod/github.com/dop251/goja@v0.0.0-20220324112439-a18ffb9c5866/parser/expression.go:240 +0x27
github.com/dop251/goja/parser.(*_parser).parseVariableDeclarationList(0xc000136000)
	/tmp/gopath126714003/pkg/mod/github.com/dop251/goja@v0.0.0-20220324112439-a18ffb9c5866/parser/expression.go:257 +0x3f
github.com/dop251/goja/parser.(*_parser).parseVarDeclarationList(0xc000136000, 0x1)
	/tmp/gopath126714003/pkg/mod/github.com/dop251/goja@v0.0.0-20220324112439-a18ffb9c5866/parser/expression.go:267 +0x2a
github.com/dop251/goja/parser.(*_parser).parseVariableStatement(0xc000136000)
	/tmp/gopath126714003/pkg/mod/github.com/dop251/goja@v0.0.0-20220324112439-a18ffb9c5866/parser/statement.go:552 +0x39
github.com/dop251/goja/parser.(*_parser).parseStatement(0xc000136000)
	/tmp/gopath126714003/pkg/mod/github.com/dop251/goja@v0.0.0-20220324112439-a18ffb9c5866/parser/statement.go:67 +0x1db
github.com/dop251/goja/parser.(*_parser).parseSourceElements(...)
	/tmp/gopath126714003/pkg/mod/github.com/dop251/goja@v0.0.0-20220324112439-a18ffb9c5866/parser/statement.go:645
github.com/dop251/goja/parser.(*_parser).parseProgram(0xc000136000)
	/tmp/gopath126714003/pkg/mod/github.com/dop251/goja@v0.0.0-20220324112439-a18ffb9c5866/parser/statement.go:655 +0x10e
github.com/dop251/goja/parser.(*_parser).parse(0xc000136000)
	/tmp/gopath126714003/pkg/mod/github.com/dop251/goja@v0.0.0-20220324112439-a18ffb9c5866/parser/parser.go:216 +0x85
github.com/dop251/goja/parser.ParseFile(0x0, {0x503116, 0x7}, {0x4e6040?, 0x52ac50?}, 0x0, {0x0, 0x0, 0x0})
	/tmp/gopath126714003/pkg/mod/github.com/dop251/goja@v0.0.0-20220324112439-a18ffb9c5866/parser/parser.go:182 +0x24c
main.main()
	/tmp/sandbox3028938662/prog.go:6 +0x45

Program exited.
```

**Comment by dop251** [comment]
Thanks for reporting!
