### ISSUE TITLE
SIGSEGV when importing goja

### ISSUE THREAD

**Issue by buergi** [dop251/goja#40]
I get SIGSEGV when importing goja, e.g. `main.go`
```
package main

import (
    _ "github.com/dop251/goja"
)

func main() {
}
```
```
$ go get
$ go run main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x56c37b]

goroutine 1 [running]:
golang.org/x/text/collate.newCollator(0x0, 0x0, 0x0)
        /home/user/go/src/golang.org/x/text/collate/option.go:30 +0x6b
golang.org/x/text/collate.New(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/user/go/src/golang.org/x/text/collate/collate.go:60 +0xbc
github.com/dop251/goja.init()
        /home/user/go/src/github.com/dop251/goja/builtin_string.go:15 +0x12d
main.init()
        <autogenerated>:1 +0x44
exit status 2
```

I use ArchLinux with go package version `2:1.9-1`, `go version go1.9 linux/amd64`, goja revision `0aeff75`.

**Comment by dop251** [comment]
See #36
