### ISSUE TITLE
`panic` when using `ExportTo`

### ISSUE THREAD

**Issue by alexec** [dop251/goja#437]
I use `ExportTo` to export a function:

```
var op Operation
vm.ExportTo(v, &op);
...
resp, err := op(Req{PathParams: pathParams, Body: body}, Ctx{DB: db})
...
```

The `db` reveals two functions, which may panic. The `panic` get dumped to the top, rather than becoming Javascript exceptions.

```
goroutine 100 [running]:
net/http.(*conn).serve.func1()
        /usr/local/opt/go/libexec/src/net/http/server.go:1850 +0x148
panic({0x1bc7e60, 0xc00011b970})
        /usr/local/opt/go/libexec/src/runtime/panic.go:890 +0x267
github.com/dop251/goja.(*Runtime).runWrapped.func1()
        /Users/acollins8/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220815083517-0c74f9139fd6/runtime.go:2406 +0x125
panic({0x1bc7e60, 0xc00011b970})
        /usr/local/opt/go/libexec/src/runtime/panic.go:890 +0x267
github.com/dop251/goja.(*vm).try.func1()
        /Users/acollins8/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220815083517-0c74f9139fd6/vm.go:626 +0xc59
panic({0x1bc7e60, 0xc00011b970})
        /usr/local/opt/go/libexec/src/runtime/panic.go:890 +0x267
github.intuit.com/acollins8/api-sandbox/internal/db.(*mongoDataSet).DB.func2()
        /Users/acollins8/go/src/github.intuit.com/acollins8/api-sandbox/internal/db/mongo.go:52 +0x2bd
reflect.Value.call({0x1b9f020, 0xc000334ae0, 0x13}, {0x1cad1af, 0x4}, {0x2329fa8, 0x0, 0x0})
        /usr/local/opt/go/libexec/src/reflect/value.go:584 +0xc76
reflect.Value.Call({0x1b9f020, 0xc000334ae0, 0x13}, {0x2329fa8, 0x0, 0x0})
        /usr/local/opt/go/libexec/src/reflect/value.go:368 +0xb7
github.com/dop251/goja.(*Runtime).wrapReflectFunc.func1({{0x1d53988, 0xc000334c90}, {0xc00033c0f0, 0x0, 0x1}})
        /Users/acollins8/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220815083517-0c74f9139fd6/runtime.go:1955 +0x2b7
github.com/dop251/goja.(*vm)._nativeCall(0xc0000d6e00, 0xc00031c1e0, 0x0)
        /Users/acollins8/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220815083517-0c74f9139fd6/vm.go:3231 +0x276
github.com/dop251/goja.call.exec(0x0, 0xc0000d6e00)
        /Users/acollins8/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220815083517-0c74f9139fd6/vm.go:3203 +0x59b
github.com/dop251/goja.(*vm).run(0xc0000d6e00)
        /Users/acollins8/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220815083517-0c74f9139fd6/vm.go:495 +0xe4
github.com/dop251/goja.(*baseJsFuncObject)._call(0xc0000be460, {0xc000338240, 0x2, 0x2}, {0x0, 0x0}, {0x0, 0x0})
        /Users/acollins8/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220815083517-0c74f9139fd6/func.go:305 +0x489
github.com/dop251/goja.(*arrowFuncObject).Call(0xc0000be460, {{0x1d54140, 0x2329cc0}, {0xc000338240, 0x2, 0x2}})
        /Users/acollins8/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220815083517-0c74f9139fd6/func.go:271 +0xa7
github.com/dop251/goja.AssertFunction.func1.1()
        /Users/acollins8/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220815083517-0c74f9139fd6/runtime.go:2366 +0xc3
github.com/dop251/goja.(*vm).try(0xc0000d6e00, 0xc0004fc368)
        /Users/acollins8/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220815083517-0c74f9139fd6/vm.go:634 +0x1e8
github.com/dop251/goja.(*Runtime).runWrapped(0xc0000cae00, 0xc0004fc368)
        /Users/acollins8/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220815083517-0c74f9139fd6/runtime.go:2410 +0xd2
github.com/dop251/goja.AssertFunction.func1({0x1d54140, 0x2329cc0}, {0xc000338240, 0x2, 0x2})
        /Users/acollins8/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220815083517-0c74f9139fd6/runtime.go:2365 +0x158
github.com/dop251/goja.(*Runtime).wrapJSFunc.func1({0xc000334b10, 0x2, 0x2})
        /Users/acollins8/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220815083517-0c74f9139fd6/runtime.go:2179 +0x1dc
github.intuit.com/acollins8/api-sandbox/internal/server.CreateServer.func1({0x1d4f590, 0xc0000be700}, 0xc0000d7900)
        /Users/acollins8/go/src/github.intuit.com/acollins8/api-sandbox/internal/server/server.go:157 +0x1273
net/http.HandlerFunc.ServeHTTP(0xc00045e910, {0x1d4f590, 0xc0000be700}, 0xc0000d7900)
        /usr/local/opt/go/libexec/src/net/http/server.go:2109 +0x43
net/http.(*ServeMux).ServeHTTP(0xc000459ec0, {0x1d4f590, 0xc0000be700}, 0xc0000d7900)
        /usr/local/opt/go/libexec/src/net/http/server.go:2487 +0x135
net/http.serverHandler.ServeHTTP({0xc0004a8000}, {0x1d4f590, 0xc0000be700}, 0xc0000d7900)
        /usr/local/opt/go/libexec/src/net/http/server.go:2947 +0x474
net/http.(*conn).serve(0xc00048dd60, {0x1d4fd38, 0xc0004ac4c0})
        /usr/local/opt/go/libexec/src/net/http/server.go:1991 +0x195c
created by net/http.(*Server).Serve
        /usr/local/opt/go/libexec/src/net/http/server.go:3102 +0x9e5

```

**Comment by dop251** [comment]
Why would it become a javascript exception?

**Comment by alexec** [comment]
> If a native Go function panics with a Value, it is thrown as a Javascript exception (and therefore can be caught):

I need to wrap in value?

**Comment by dop251** [comment]
Yes. If the panic argument is a `Value` it's an exception. Otherwise it's just a normal Go panic.

**Comment by alexec** [comment]
Ok. It’d be cool to have an example in the read me to make it really clear. But my problem is solved.

**Comment by alexec** [comment]
How can I create a `Value`? I could not find an example.

**Comment by dop251** [comment]
Use [Runtime.ToValue](https://pkg.go.dev/github.com/dop251/goja#Runtime.ToValue)

**Comment by alexec** [comment]
Ah. I used `vm.NewGoError(error)` but same.
