### ISSUE TITLE
Debugging goja stacktraces

### ISSUE THREAD

**Issue by jeromegn** [dop251/goja#49]
For example:

```
2017/11/24 16:18:52 values: [normal throw]
2017/11/24 16:18:52  0: goja.enterFuncStashless({1 3})
2017/11/24 16:18:52  1: goja.try({15 0 false})
2017/11/24 16:18:52  2: goja._newObject({})
2017/11/24 16:18:52  3: goja.loadVal(0)
2017/11/24 16:18:52  4: goja.setProp1(type)
2017/11/24 16:18:52  5: goja.loadStack(-1)
2017/11/24 16:18:52  6: goja._dup({})
2017/11/24 16:18:52  7: goja.getPropCallee(call)
2017/11/24 16:18:52 run buildnext.then called
2017/11/24 16:18:52  8: goja.loadStack(-2)
2017/11/24 16:18:52  9: goja.loadStack(-3)
2017/11/24 16:18:52  10: goja.call(2)
2017/11/24 16:18:52  11: goja.setProp1(arg)
2017/11/24 16:18:52  12: goja._halt({})
2017/11/24 16:18:52  13: goja._retStashless({})
2017/11/24 16:18:52  14: goja._halt({})
2017/11/24 16:18:52  15: goja.jump(11)
2017/11/24 16:18:52  16: goja.storeStack(1)
2017/11/24 16:18:52  17: goja._pop({})
2017/11/24 16:18:52  18: goja._newObject({})
2017/11/24 16:18:52  19: goja.loadVal(1)
2017/11/24 16:18:52  20: goja.setProp1(type)
2017/11/24 16:18:52  21: goja.loadStack(1)
2017/11/24 16:18:52  22: goja.setProp1(arg)
2017/11/24 16:18:52  23: goja._halt({})
2017/11/24 16:18:52  24: goja._retStashless({})
2017/11/24 16:18:52  25: goja._halt({})
2017/11/24 16:18:52  26: goja._loadUndef({})
2017/11/24 16:18:52  27: goja._retStashless({})
2017/11/24 16:18:52 values: [true Promise can't be resolved itself 1 false]
2017/11/24 16:18:52  0: goja.enterFunc(1)
2017/11/24 16:18:52  1: goja.bindName(value)
2017/11/24 16:18:52  2: goja.bindName(promise)
2017/11/24 16:18:52  3: goja.bindName(then)
2017/11/24 16:18:52  4: goja.bindName( __tmp0)
2017/11/24 16:18:52  5: goja.loadStack(0)
2017/11/24 16:18:52  6: goja.setLocal(1)
2017/11/24 16:18:52  7: goja._pop({})
2017/11/24 16:18:52  8: goja.getLocal(1)
2017/11/24 16:18:52  9: goja.getProp(_d)
2017/11/24 16:18:52  10: goja.jne(3)
2017/11/24 16:18:52  11: goja._loadUndef({})
2017/11/24 16:18:52  12: goja._ret({})
2017/11/24 16:18:52  13: goja.getLocal(1)
2017/11/24 16:18:52  14: goja.loadVal(0)
2017/11/24 16:18:52  15: goja.setPropStrict(_d)
2017/11/24 16:18:52  16: goja._pop({})
2017/11/24 16:18:52  17: goja.getLocal(1)
2017/11/24 16:18:52  18: goja.getProp(_w)
2017/11/24 16:18:52  19: goja.jeq1(3)
2017/11/24 16:18:52  20: goja._pop({})
2017/11/24 16:18:52  21: goja.getLocal(1)
2017/11/24 16:18:52  22: goja.setLocal(1)
2017/11/24 16:18:52  23: goja._pop({})
2017/11/24 16:18:52  24: goja.try({38 0 false})
2017/11/24 16:18:52  25: goja.getLocal(1)
2017/11/24 16:18:52  26: goja.getLocal(0)
2017/11/24 16:18:52  27: goja._op_strict_eq({})
2017/11/24 16:18:52  28: goja.jne(6)
2017/11/24 16:18:52  29: goja._loadUndef({})
2017/11/24 16:18:52  30: goja.getLocal(16777235)
2017/11/24 16:18:52  31: goja.loadVal(1)
2017/11/24 16:18:52  32: goja.call(1)
2017/11/24 16:18:52  33: goja._throw({})
2017/11/24 16:18:52  34: goja._loadUndef({})
2017/11/24 16:18:52  35: goja.getLocal(16777247)
2017/11/24 16:18:52  36: goja.getLocal(0)
2017/11/24 16:18:52  37: goja.call(1)
2017/11/24 16:18:52  38: goja.setLocal(2)
2017/11/24 16:18:52  39: goja.jne(7)
2017/11/24 16:18:52  40: goja._loadUndef({})
2017/11/24 16:18:52  41: goja.getLocal(16777230)
2017/11/24 16:18:52  42: *goja.newFunc(&{0xc422276de0  0 true 144833 145075})
2017/11/24 16:18:52 values: [false 1]
2017/11/24 16:18:52 > 0: goja.enterFuncStashless({2 0})
2017/11/24 16:18:52 > 1: goja._newObject({})
2017/11/24 16:18:52 > 2: goja.getLocal(1)
2017/11/24 16:18:52 > 3: goja.setProp1(_w)
2017/11/24 16:18:52 > 4: goja.loadVal(0)
2017/11/24 16:18:52 > 5: goja.setProp1(_d)
2017/11/24 16:18:52 > 6: goja.storeStack(1)
2017/11/24 16:18:52 > 7: goja._pop({})
2017/11/24 16:18:52 > 8: goja.try({21 0 false})
2017/11/24 16:18:52 > 9: goja.getLocal(2)
2017/11/24 16:18:52 > 10: goja._dup({})
2017/11/24 16:18:52 > 11: goja.getPropCallee(call)
2017/11/24 16:18:52 > 12: goja.getLocal(0)
2017/11/24 16:18:52 > 13: goja._loadUndef({})
2017/11/24 16:18:52 > 14: goja.getLocal(16777221)
2017/11/24 16:18:52 > 15: goja.getLocal(16777253)
2017/11/24 16:18:52 > 16: goja.loadStack(1)
2017/11/24 16:18:52 > 17: goja.loadVal(1)
2017/11/24 16:18:52 > 18: goja.call(3)
2017/11/24 16:18:52 > 19: goja._loadUndef({})
2017/11/24 16:18:52 > 20: goja.getLocal(16777221)
2017/11/24 16:18:52 > 21: goja.getLocal(16777252)
2017/11/24 16:18:52 > 22: goja.loadStack(1)
2017/11/24 16:18:52 > 23: goja.loadVal(1)
2017/11/24 16:18:52 > 24: goja.call(3)
2017/11/24 16:18:52 > 25: goja.call(3)
2017/11/24 16:18:52 > 26: goja._pop({})
2017/11/24 16:18:52 > 27: goja._halt({})
2017/11/24 16:18:52 > 28: goja.jump(11)
2017/11/24 16:18:52 > 29: goja.storeStack(2)
2017/11/24 16:18:52 > 30: goja._pop({})
2017/11/24 16:18:52 > 31: goja.getLocal(16777252)
2017/11/24 16:18:52 > 32: goja._dup({})
2017/11/24 16:18:52 > 33: goja.getPropCallee(call)
2017/11/24 16:18:52 > 34: goja.loadStack(1)
2017/11/24 16:18:52 > 35: goja.loadStack(2)
2017/11/24 16:18:52 > 36: goja.call(2)
2017/11/24 16:18:52 > 37: goja._pop({})
2017/11/24 16:18:52 > 38: goja._halt({})
2017/11/24 16:18:52 > 39: goja._loadUndef({})
2017/11/24 16:18:52 > 40: goja._retStashless({})
2017/11/24 16:18:52  43: goja.call(1)
2017/11/24 16:18:52  44: goja._pop({})
2017/11/24 16:18:52  45: goja.jump(15)
2017/11/24 16:18:52  46: goja.getLocal(1)
2017/11/24 16:18:52  47: goja.getLocal(0)
2017/11/24 16:18:52  48: goja.setPropStrict(_v)
2017/11/24 16:18:52  49: goja._pop({})
2017/11/24 16:18:52  50: goja.getLocal(1)
2017/11/24 16:18:52  51: goja.loadVal(2)
2017/11/24 16:18:52  52: goja.setPropStrict(_s)
2017/11/24 16:18:52  53: goja._pop({})
2017/11/24 16:18:52  54: goja._loadUndef({})
2017/11/24 16:18:52  55: goja.getLocal(16777248)
2017/11/24 16:18:52  56: goja.getLocal(1)
2017/11/24 16:18:52  57: goja.loadVal(3)
2017/11/24 16:18:52  58: goja.call(2)
2017/11/24 16:18:52  59: goja._pop({})
2017/11/24 16:18:52  60: goja._halt({})
2017/11/24 16:18:52  61: goja.jump(15)
2017/11/24 16:18:52  62: goja.setLocal(3)
2017/11/24 16:18:52  63: goja._pop({})
2017/11/24 16:18:52  64: goja.getLocal(16777252)
2017/11/24 16:18:52  65: goja._dup({})
2017/11/24 16:18:52  66: goja.getPropCallee(call)
2017/11/24 16:18:52  67: goja._newObject({})
2017/11/24 16:18:52  68: goja.getLocal(1)
2017/11/24 16:18:52  69: goja.setProp1(_w)
2017/11/24 16:18:52  70: goja.loadVal(3)
2017/11/24 16:18:52  71: goja.setProp1(_d)
2017/11/24 16:18:52  72: goja.getLocal(3)
2017/11/24 16:18:52  73: goja.call(2)
2017/11/24 16:18:52  74: goja._pop({})
2017/11/24 16:18:52  75: goja._halt({})
2017/11/24 16:18:52  76: goja._loadUndef({})
2017/11/24 16:18:52  77: goja._ret({})
2017/11/24 16:18:52 values: [2 1 true Promise-chain cycle]
2017/11/24 16:18:52  0: goja.enterFuncStashless({7 1})
2017/11/24 16:18:52  1: goja.getLocal(1)
2017/11/24 16:18:52  2: goja.jne(4)
2017/11/24 16:18:52  3: goja.loadStack(-1)
2017/11/24 16:18:52  4: goja.getProp(ok)
2017/11/24 16:18:52  5: goja.jump(3)
2017/11/24 16:18:52  6: goja.loadStack(-1)
2017/11/24 16:18:52  7: goja.getProp(fail)
2017/11/24 16:18:52  8: goja.storeStack(1)
2017/11/24 16:18:52  9: goja._pop({})
2017/11/24 16:18:52  10: goja.loadStack(-1)
2017/11/24 16:18:52  11: goja.getProp(resolve)
2017/11/24 16:18:52  12: goja.storeStack(2)
2017/11/24 16:18:52  13: goja._pop({})
2017/11/24 16:18:52  14: goja.loadStack(-1)
2017/11/24 16:18:52  15: goja.getProp(reject)
2017/11/24 16:18:52  16: goja.storeStack(3)
2017/11/24 16:18:52  17: goja._pop({})
2017/11/24 16:18:52  18: goja.loadStack(-1)
2017/11/24 16:18:52  19: goja.getProp(domain)
2017/11/24 16:18:52  20: goja.storeStack(4)
2017/11/24 16:18:52  21: goja._pop({})
2017/11/24 16:18:52  22: goja.try({90 0 false})
2017/11/24 16:18:52  23: goja.loadStack(1)
2017/11/24 16:18:52  24: goja.jne(81)
2017/11/24 16:18:52  25: goja.getLocal(1)
2017/11/24 16:18:52  26: goja._not({})
2017/11/24 16:18:52  27: goja.jne(15)
2017/11/24 16:18:52  28: goja.getLocal(16777216)
2017/11/24 16:18:52  29: goja.getProp(_h)
2017/11/24 16:18:52  30: goja.loadVal(0)
2017/11/24 16:18:52  31: goja._op_eq({})
2017/11/24 16:18:52  32: goja.jne(6)
2017/11/24 16:18:52  33: goja._loadUndef({})
2017/11/24 16:18:52  34: goja.getLocal(33554467)
2017/11/24 16:18:52  35: goja.getLocal(16777216)
2017/11/24 16:18:52  36: goja.call(1)
2017/11/24 16:18:52  37: goja._pop({})
2017/11/24 16:18:52  38: goja.getLocal(16777216)
2017/11/24 16:18:52  39: goja.loadVal(1)
2017/11/24 16:18:52  40: goja.setPropStrict(_h)
2017/11/24 16:18:52  41: goja._pop({})
2017/11/24 16:18:52  42: goja.loadStack(1)
2017/11/24 16:18:52  43: goja.loadVal(2)
2017/11/24 16:18:52  44: goja._op_strict_eq({})
2017/11/24 16:18:52  45: goja.jne(5)
2017/11/24 16:18:52  46: goja.getLocal(0)
2017/11/24 16:18:52  47: goja.storeStack(5)
2017/11/24 16:18:52  48: goja._pop({})
2017/11/24 16:18:52  49: goja.jump(21)
2017/11/24 16:18:52  50: goja.loadStack(4)
2017/11/24 16:18:52  51: goja.jne(6)
2017/11/24 16:18:52  52: goja.loadStack(4)
2017/11/24 16:18:52  53: goja._dup({})
2017/11/24 16:18:52  54: goja.getPropCallee(enter)
2017/11/24 16:18:52  55: goja.call(0)
2017/11/24 16:18:52  56: goja._pop({})
2017/11/24 16:18:52  57: goja._loadUndef({})
2017/11/24 16:18:52  58: goja.loadStack(1)
2017/11/24 16:18:52  59: goja.getLocal(0)
2017/11/24 16:18:52  60: goja.call(1)
2017/11/24 16:18:52  61: goja.storeStack(5)
2017/11/24 16:18:52  62: goja._pop({})
2017/11/24 16:18:52  63: goja.loadStack(4)
2017/11/24 16:18:52  64: goja.jne(6)
2017/11/24 16:18:52  65: goja.loadStack(4)
2017/11/24 16:18:52  66: goja._dup({})
2017/11/24 16:18:52  67: goja.getPropCallee(exit)
2017/11/24 16:18:52  68: goja.call(0)
2017/11/24 16:18:52  69: goja._pop({})
2017/11/24 16:18:52  70: goja.loadStack(5)
2017/11/24 16:18:52  71: goja.loadStack(-1)
2017/11/24 16:18:52  72: goja.getProp(promise)
2017/11/24 16:18:52  73: goja._op_strict_eq({})
2017/11/24 16:18:52  74: goja.jne(10)
2017/11/24 16:18:52  75: goja._loadUndef({})
2017/11/24 16:18:52  76: goja.loadStack(3)
2017/11/24 16:18:52  77: goja._loadUndef({})
2017/11/24 16:18:52  78: goja.getLocal(33554451)
2017/11/24 16:18:52  79: goja.loadVal(3)
2017/11/24 16:18:52  80: goja.call(1)
2017/11/24 16:18:52  81: goja.call(1)
2017/11/24 16:18:52  82: goja._pop({})
2017/11/24 16:18:52  83: goja.jump(21)
2017/11/24 16:18:52  84: goja._loadUndef({})
2017/11/24 16:18:52  85: goja.getLocal(33554463)
2017/11/24 16:18:52  86: goja.loadStack(5)
2017/11/24 16:18:52  87: goja.call(1)
2017/11/24 16:18:52  88: goja.storeStack(6)
2017/11/24 16:18:52  89: goja.jne(10)
2017/11/24 16:18:52  90: goja.loadStack(6)
2017/11/24 16:18:52  91: goja._dup({})
2017/11/24 16:18:52  92: goja.getPropCallee(call)
2017/11/24 16:18:52  93: goja.loadStack(5)
2017/11/24 16:18:52  94: goja.loadStack(2)
2017/11/24 16:18:52  95: goja.loadStack(3)
2017/11/24 16:18:52  96: goja.call(3)
2017/11/24 16:18:52  97: goja._pop({})
2017/11/24 16:18:52  98: goja.jump(6)
2017/11/24 16:18:52  99: goja._loadUndef({})
2017/11/24 16:18:52  100: goja.loadStack(2)
2017/11/24 16:18:52  101: goja.loadStack(5)
2017/11/24 16:18:52  102: goja.call(1)
2017/11/24 16:18:52  103: goja._pop({})
2017/11/24 16:18:52  104: goja.jump(6)
2017/11/24 16:18:52  105: goja._loadUndef({})
2017/11/24 16:18:52  106: goja.loadStack(3)
2017/11/24 16:18:52  107: goja.getLocal(0)
2017/11/24 16:18:52  108: goja.call(1)
2017/11/24 16:18:52  109: goja._pop({})
2017/11/24 16:18:52  110: goja._halt({})
2017/11/24 16:18:52  111: goja.jump(9)
2017/11/24 16:18:52  112: goja.storeStack(7)
2017/11/24 16:18:52  113: goja._pop({})
2017/11/24 16:18:52  114: goja._loadUndef({})
2017/11/24 16:18:52  115: goja.loadStack(3)
2017/11/24 16:18:52  116: goja.loadStack(7)
2017/11/24 16:18:52  117: goja.call(1)
2017/11/24 16:18:52  118: goja._pop({})
2017/11/24 16:18:52  119: goja._halt({})
2017/11/24 16:18:52  120: goja._loadUndef({})
2017/11/24 16:18:52  121: goja._retStashless({})
2017/11/24 16:18:52 values: []
2017/11/24 16:18:52  0: goja.enterFuncStashless({3 0})
2017/11/24 16:18:52  1: goja.getLocal(16777224)
2017/11/24 16:18:52  2: goja.jneq1(5)
2017/11/24 16:18:52  3: goja._pop({})
2017/11/24 16:18:52  4: goja.getLocal(16777222)
2017/11/24 16:18:52  5: goja.getProp(domain)
2017/11/24 16:18:52  6: goja.storeStack(1)
2017/11/24 16:18:52  7: goja.jne(6)
2017/11/24 16:18:52  8: goja.loadStack(1)
2017/11/24 16:18:52  9: goja._dup({})
2017/11/24 16:18:52  10: goja.getPropCallee(exit)
2017/11/24 16:18:52  11: goja.call(0)
2017/11/24 16:18:52  12: goja._pop({})
2017/11/24 16:18:52  13: goja.getLocal(0)
2017/11/24 16:18:52  14: goja.jne(32)
2017/11/24 16:18:52  15: goja.getLocal(0)
2017/11/24 16:18:52  16: goja.getProp(fn)
2017/11/24 16:18:52  17: goja.storeStack(2)
2017/11/24 16:18:52  18: goja._pop({})
2017/11/24 16:18:52  19: goja.getLocal(0)
2017/11/24 16:18:52  20: goja.getProp(next)
2017/11/24 16:18:52  21: goja.setLocal(0)
2017/11/24 16:18:52  22: goja._pop({})
2017/11/24 16:18:52  23: goja.try({7 0 false})
2017/11/24 16:18:52  24: goja._loadUndef({})
2017/11/24 16:18:52  25: goja.loadStack(2)
2017/11/24 16:18:52  26: goja.call(0)
2017/11/24 16:18:52  27: goja._pop({})
2017/11/24 16:18:52  28: goja._halt({})
2017/11/24 16:18:52  29: goja.jump(16)
2017/11/24 16:18:52  30: goja.storeStack(3)
2017/11/24 16:18:52  31: goja._pop({})
2017/11/24 16:18:52  32: goja.getLocal(0)
2017/11/24 16:18:52  33: goja.jne(6)
2017/11/24 16:18:52  34: goja._loadUndef({})
2017/11/24 16:18:52  35: goja.getLocal(2)
2017/11/24 16:18:52  36: goja.call(0)
2017/11/24 16:18:52  37: goja._pop({})
2017/11/24 16:18:52  38: goja.jump(4)
2017/11/24 16:18:52  39: goja.getVar1(undefined)
2017/11/24 16:18:52  40: goja.setLocal(1)
2017/11/24 16:18:52  41: goja._pop({})
2017/11/24 16:18:52  42: goja.loadStack(3)
2017/11/24 16:18:52  43: goja._throw({})
2017/11/24 16:18:52  44: goja._halt({})
2017/11/24 16:18:52  45: goja.jump(-32)
2017/11/24 16:18:52  46: goja.getVar1(undefined)
2017/11/24 16:18:52  47: goja.setLocal(1)
2017/11/24 16:18:52  48: goja._pop({})
2017/11/24 16:18:52  49: goja.loadStack(1)
2017/11/24 16:18:52  50: goja.jne(6)
2017/11/24 16:18:52  51: goja.loadStack(1)
2017/11/24 16:18:52  52: goja._dup({})
2017/11/24 16:18:52  53: goja.getPropCallee(enter)
2017/11/24 16:18:52  54: goja.call(0)
2017/11/24 16:18:52  55: goja._pop({})
2017/11/24 16:18:52  56: goja._loadUndef({})
2017/11/24 16:18:52  57: goja._retStashless({})
panic: runtime error: index out of range [recovered]
	panic: Panic at 10: runtime error: index out of range [recovered]
	panic: Panic at 25: Panic at 10: runtime error: index out of range [recovered]
	panic: Panic at 23: Panic at 25: Panic at 10: runtime error: index out of range [recovered]
	panic: Panic at 24: Panic at 23: Panic at 25: Panic at 10: runtime error: index out of range

goroutine 46 [running]:
github.com/dop251/goja.(*vm).try.func1(0xc420263860, 0x0, 0xc426dc7e08, 0x0, 0x0, 0x0, 0xc426dc7e60)
	github.com/dop251/goja/vm.go:364 +0x4b4
panic(0x17cff00, 0xc422820380)
	/usr/local/opt/go/libexec/src/runtime/panic.go:491 +0x283
github.com/dop251/goja.(*vm).try.func1(0xc420263860, 0x6, 0xc426dc76c0, 0x19, 0x0, 0x0, 0xc426dc7718)
	github.com/dop251/goja/vm.go:364 +0x4b4
panic(0x17cff00, 0xc422820360)
	/usr/local/opt/go/libexec/src/runtime/panic.go:491 +0x283
github.com/dop251/goja.(*vm).try.func1(0xc420263860, 0x8, 0xc426dc74c0, 0x25, 0x0, 0x0, 0xc426dc7518)
	github.com/dop251/goja/vm.go:364 +0x4b4
panic(0x17cff00, 0xc422751fe0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:491 +0x283
github.com/dop251/goja.(*vm).try.func1(0xc420263860, 0xb, 0xc426dc6ee8, 0x2e, 0x0, 0x0, 0xc426dc6f40)
	github.com/dop251/goja/vm.go:364 +0x4b4
panic(0x17e8720, 0x1f3db30)
	/usr/local/opt/go/libexec/src/runtime/panic.go:491 +0x283
github.com/dop251/goja.(*vm).popCtx(...)
	github.com/dop251/goja/vm.go:427
github.com/dop251/goja.(*vm)._nativeCall(0xc420263860, 0xc420c05b80, 0x2)
	github.com/dop251/goja/vm.go:1834 +0x858
github.com/dop251/goja.call.exec(0x2, 0xc420263860)
	github.com/dop251/goja/vm.go:1810 +0x6b3
github.com/dop251/goja.(*call).exec(0xc42048b02c, 0xc420263860)
	<autogenerated>:1 +0x44
github.com/dop251/goja.(*vm).run(0xc420263860)
	github.com/dop251/goja/vm.go:288 +0x51
github.com/dop251/goja.(*funcObject).Call(0xc420b64600, 0x1d880e0, 0xc42175fb40, 0xc420f75690, 0x1, 0xe5, 0x20, 0x179c440)
	github.com/dop251/goja/func.go:130 +0x3c8
github.com/dop251/goja.(*funcObject).Call-fm(0x1d880e0, 0xc42175fb40, 0xc420f75690, 0x1, 0xe5, 0x1012b70, 0x1f52360)
	github.com/dop251/goja/builtin_function.go:120 +0x51
github.com/dop251/goja.(*Runtime).functionproto_call(0xc425d06f00, 0x1d880e0, 0xc4245a4120, 0xc420f75680, 0x2, 0xe6, 0xc420a11c68, 0x4)
	github.com/dop251/goja/builtin_function.go:71 +0x155
github.com/dop251/goja.(*Runtime).(github.com/dop251/goja.functionproto_call)-fm(0x1d880e0, 0xc4245a4120, 0xc420f75680, 0x2, 0xe6, 0x13d3f43, 0x17e1340)
	github.com/dop251/goja/builtin_function.go:160 +0x51
github.com/dop251/goja.(*vm)._nativeCall(0xc420263860, 0xc422d2aa50, 0x2)
	github.com/dop251/goja/vm.go:1826 +0x2ec
github.com/dop251/goja.call.exec(0x2, 0xc420263860)
	github.com/dop251/goja/vm.go:1810 +0x6b3
github.com/dop251/goja.(*call).exec(0xc4209e56fc, 0xc420263860)
	<autogenerated>:1 +0x44
github.com/dop251/goja.(*vm).run(0xc420263860)
	github.com/dop251/goja/vm.go:288 +0x51
github.com/dop251/goja.(*vm).(github.com/dop251/goja.run)-fm()
	github.com/dop251/goja/vm.go:375 +0x2a
github.com/dop251/goja.(*vm).try(0xc420263860, 0xc427c92f48, 0x0)
	github.com/dop251/goja/vm.go:370 +0x119
github.com/dop251/goja.(*vm).runTry(0xc420263860, 0xc424f19230)
	github.com/dop251/goja/vm.go:375 +0x46
github.com/dop251/goja.try.exec(0x26, 0x0, 0xc420263860)
	github.com/dop251/goja/vm.go:2245 +0x51
github.com/dop251/goja.(*try).exec(0xc42121f070, 0xc420263860)
	<autogenerated>:1 +0x53
github.com/dop251/goja.(*vm).run(0xc420263860)
	github.com/dop251/goja/vm.go:288 +0x51
github.com/dop251/goja.(*funcObject).Call(0xc420b65a40, 0x1d880e0, 0xc4235d1060, 0xc420f755b0, 0x1, 0xf3, 0x1d880e0, 0xc4235d1160)
	github.com/dop251/goja/func.go:130 +0x3c8
github.com/dop251/goja.(*funcObject).Call-fm(0x1d880e0, 0xc4235d1060, 0xc420f755b0, 0x1, 0xf3, 0x1d880e0, 0xc4235d1160)
	github.com/dop251/goja/builtin_function.go:120 +0x51
github.com/dop251/goja.(*Runtime).functionproto_call(0xc425d06f00, 0x1d880e0, 0xc4245a4ba0, 0xc420f755a0, 0x2, 0xf4, 0xc420a0b896, 0x4)
	github.com/dop251/goja/builtin_function.go:71 +0x155
github.com/dop251/goja.(*Runtime).(github.com/dop251/goja.functionproto_call)-fm(0x1d880e0, 0xc4245a4ba0, 0xc420f755a0, 0x2, 0xf4, 0x13d3f43, 0x17e1340)
	github.com/dop251/goja/builtin_function.go:160 +0x51
github.com/dop251/goja.(*vm)._nativeCall(0xc420263860, 0xc422d2aa50, 0x2)
	github.com/dop251/goja/vm.go:1826 +0x2ec
github.com/dop251/goja.call.exec(0xffffffff00000002, 0xc420263860)
	github.com/dop251/goja/vm.go:1810 +0x6b3
github.com/dop251/goja.(*call).exec(0xc4212380dc, 0xc420263860)
	<autogenerated>:1 +0x44
github.com/dop251/goja.(*vm).run(0xc420263860)
	github.com/dop251/goja/vm.go:288 +0x51
github.com/dop251/goja.(*vm).(github.com/dop251/goja.run)-fm()
	github.com/dop251/goja/vm.go:375 +0x2a
github.com/dop251/goja.(*vm).try(0xc420263860, 0xc427c93520, 0x0)
	github.com/dop251/goja/vm.go:370 +0x119
github.com/dop251/goja.(*vm).runTry(0xc420263860, 0xc424f19380)
	github.com/dop251/goja/vm.go:375 +0x46
github.com/dop251/goja.try.exec(0x5a, 0x0, 0xc420263860)
	github.com/dop251/goja/vm.go:2245 +0x51
github.com/dop251/goja.(*try).exec(0xc42121e380, 0xc420263860)
	<autogenerated>:1 +0x53
github.com/dop251/goja.(*vm).run(0xc420263860)
	github.com/dop251/goja/vm.go:288 +0x51
github.com/dop251/goja.(*vm).(github.com/dop251/goja.run)-fm()
	github.com/dop251/goja/vm.go:375 +0x2a
github.com/dop251/goja.(*vm).try(0xc420263860, 0xc427c93720, 0x0)
	github.com/dop251/goja/vm.go:370 +0x119
github.com/dop251/goja.(*vm).runTry(0xc420263860, 0xc422ab1e00)
	github.com/dop251/goja/vm.go:375 +0x46
github.com/dop251/goja.try.exec(0x7, 0x0, 0xc420263860)
	github.com/dop251/goja/vm.go:2245 +0x51
github.com/dop251/goja.(*try).exec(0xc4209e53e0, 0xc420263860)
	<autogenerated>:1 +0x53
github.com/dop251/goja.(*vm).run(0xc420263860)
	github.com/dop251/goja/vm.go:288 +0x51
github.com/dop251/goja.(*funcObject).Call(0xc420b64480, 0x1d885e0, 0xc420018d90, 0xc420f75360, 0x1, 0x118, 0x1d88720, 0x1f71e60)
	github.com/dop251/goja/func.go:130 +0x3c8
github.com/dop251/goja.(*funcObject).Call-fm(0x1d885e0, 0xc420018d90, 0xc420f75360, 0x1, 0x118, 0x1d88720, 0x1f71e60)
	github.com/dop251/goja/builtin_function.go:120 +0x51
github.com/dop251/goja.(*Runtime).functionproto_call(0xc425d06f00, 0x1d880e0, 0xc4245a40a0, 0xc420f75350, 0x2, 0x119, 0xc420a0b896, 0x4)
	github.com/dop251/goja/builtin_function.go:71 +0x155
github.com/dop251/goja.(*Runtime).(github.com/dop251/goja.functionproto_call)-fm(0x1d880e0, 0xc4245a40a0, 0xc420f75350, 0x2, 0x119, 0x13d3f43, 0x17e1340)
	github.com/dop251/goja/builtin_function.go:160 +0x51
github.com/dop251/goja.(*vm)._nativeCall(0xc420263860, 0xc422d2aa50, 0x2)
	github.com/dop251/goja/vm.go:1826 +0x2ec
github.com/dop251/goja.call.exec(0xffffffff00000002, 0xc420263860)
	github.com/dop251/goja/vm.go:1810 +0x6b3
github.com/dop251/goja.(*call).exec(0xc4212380dc, 0xc420263860)
	<autogenerated>:1 +0x44
github.com/dop251/goja.(*vm).run(0xc420263860)
	github.com/dop251/goja/vm.go:288 +0x51
github.com/dop251/goja.(*funcObject).Call(0xc425be83c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc427c93d90, 0xc42002b900)
	github.com/dop251/goja/func.go:130 +0x3c8
github.com/dop251/goja.(*funcObject).Call-fm(0x0, 0x0, 0x0, 0x0, 0x0, 0x102ad99, 0xc4201e3fb0)
	github.com/dop251/goja/builtin_function.go:120 +0x51
github.com/dop251/goja.AssertFunction.func1.1()
	github.com/dop251/goja/runtime.go:1374 +0xb6
github.com/dop251/goja.(*vm).try(0xc420263860, 0xc427c93e80, 0x0)
	github.com/dop251/goja/vm.go:370 +0x119
github.com/dop251/goja.AssertFunction.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc427c93f30, 0x0)
	github.com/dop251/goja/runtime.go:1373 +0xdd
github.com/dop251/goja_nodejs/eventloop.(*EventLoop).doTimeout(0xc42087e720, 0xc42448e030)
	github.com/dop251/goja_nodejs/eventloop/eventloop.go:178 +0x6d
github.com/dop251/goja_nodejs/eventloop.(*EventLoop).addTimeout.func1.1()
	github.com/dop251/goja_nodejs/eventloop/eventloop.go:156 +0xad
github.com/dop251/goja_nodejs/eventloop.(*EventLoop).run(0xc42087e720, 0x1)
	github.com/dop251/goja_nodejs/eventloop/eventloop.go:137 +0x72
created by github.com/dop251/goja_nodejs/eventloop.(*EventLoop).Start
	github.com/dop251/goja_nodejs/eventloop/eventloop.go:94 +0x44
```

**Note:** Line numbers may not fit the eventloop's code available on github, I've added a lot of fmt.Println to try and debug this, but I haven't changed actual code.

**I think** I've been running all code that interacts with a `*goja.Runtime` inside `RunOnLoop`. My code is transpiled (babel) and then the runtime is polyfilled heavily, but as far as I know, it should work fine. It's been working fine for the most part.

Here's an example of my `xhr` polyfill: https://gist.github.com/jeromegn/cb76ba14437ab688074c6b2d607d358d (just in case you see anything that would break here)

My question is: Is there any way to make sense of this stacktrace? As far as I understand, the `Panic at <n>` references the stack level in the previous trace. Except I have no idea how to correlate this with actual JS code.

Doesn't goja keep track of the line and column of the source when making its AST?

**Comment by dop251** [comment]
You are running js code in two parallel goroutines. I know this because of where the panic occurred (vm.go:427). There is no way it would fail on this line but not on the previous line unless vm.callStack was modified in between. 

I also know it because of a stray log message that was printed during the code dump:

2017/11/24 16:18:52 run buildnext.then called

As for the js stacktrace, it is possible to create an Exception, set the stacktrace on it just like it's done for catch-able panics and print it by calling exception.String(). The reason it's not done at the moment is I guess because it's normally not possible to trigger this with a JS code. Judging by the code dump the panic occurred when calling  an exit() method on something.

Hope this helps.

**Comment by jeromegn** [comment]
It helps, thanks!

As I said, I'm using the eventloop from the goja_nodejs project. I bet I "missed a spot" where I'm doing something outside of the loop. Do you know exactly which operations I can do outside of a loop? Are any interactions with values safe outside of the loop? If not, I guess I need to `.Export()` all values I want to use outside of the loop.

The gist I shared (https://gist.github.com/jeromegn/cb76ba14437ab688074c6b2d607d358d) shows my usage of the loop and doing stuff asynchronously. I think the way that it's made is fairly safe and I would expect that's not the part that explodes.

It's a little hard to track where the code is failing (that `exit` method) since I'm using thousands of lines of polyfills and I'm also transpiling my code.

**Comment by dop251** [comment]
Objects are based on maps so the same rules apply: concurrent reads are ok, everything else isn't. In your case however, it looks like there are concurrent method invocations, not map access. If you have a test case, you could try running it with the race detector, it may help.

**Comment by dop251** [comment]
I assume the problem is solved this way or another. Feel free to re-open if you have any more questions.
