### ISSUE TITLE
Crash with Get and Interrupt

### ISSUE THREAD

**Issue by liclac** [dop251/goja#54]
```go
func TestInterrupt(t *testing.T) {
	rt := goja.New()
	_, err := rt.RunString(`
		var fn = function() {
			while (true) {}
		};
	`)
	if !assert.NoError(t, err) {
		return
	}
	fn, ok := goja.AssertFunction(rt.Get("fn"))
	if !assert.True(t, ok) {
		return
	}
	go func() {
		<-time.After(1 * time.Second)
		rt.Interrupt(errors.New("hi"))
	}()
	v, err := fn(goja.Undefined())
	assert.Nil(t, v)
	assert.EqualError(t, err, "hi")
}
```

Causes a panic:

```
panic: <nil> [recovered]
	panic: <nil> [recovered]
	panic: <nil>

goroutine 4 [running]:
testing.tRunner.func1(0xc4210af0e0)
	/usr/lib/go/src/testing/testing.go:711 +0x2d2
panic(0xaa5820, 0xc4212d5740)
	/usr/lib/go/src/runtime/panic.go:491 +0x283
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try.func1(0xc4204ceea0, 0x0, 0xc422b27e60, 0x0, 0x0, 0x0, 0xc422b27eb8)
	/home/emily/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:356 +0x4a4
panic(0xaa5820, 0xc4212d5740)
	/usr/lib/go/src/runtime/panic.go:491 +0x283
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).run(0xc4204ceea0)
	/home/emily/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:299 +0x183
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call(0xc420387c80, 0xfd2b40, 0x117fd20, 0x0, 0x0, 0x0, 0x0, 0xc420024000)
	/home/emily/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/func.go:130 +0x3c8
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*funcObject).Call-fm(0xfd2b40, 0x117fd20, 0x0, 0x0, 0x0, 0x42bd99, 0xc420feca40)
	/home/emily/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/builtin_function.go:120 +0x51
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1.1()
	/home/emily/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1374 +0xb6
github.com/loadimpact/k6/vendor/github.com/dop251/goja.(*vm).try(0xc4204ceea0, 0xc422b27ed8, 0x0)
	/home/emily/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/vm.go:370 +0x119
github.com/loadimpact/k6/vendor/github.com/dop251/goja.AssertFunction.func1(0xfd2b40, 0x117fd20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19829e1200000001, 0x5a222c1d)
	/home/emily/go/src/github.com/loadimpact/k6/vendor/github.com/dop251/goja/runtime.go:1373 +0xdd
github.com/loadimpact/k6/js.TestInterrupt(0xc4210af0e0)
	/home/emily/go/src/github.com/loadimpact/k6/js/runner_test.go:259 +0x152
testing.tRunner(0xc4210af0e0, 0xb8eb10)
	/usr/lib/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:789 +0x2de
```

It doesn't happen if you use a value returned from `Run*`, only if you get it with `Get`.

**Comment by dop251** [comment]
Hi. Can you please explain what you mean by "if you use a value returned from Run*"? It behaves exactly the same way for me...

**Comment by liclac** [comment]
Hm, it does for me too now, I could'a sworn I managed to *not* make it crash just a few days ago, but I can't remember how. Nevermind.
