### ISSUE TITLE
panic: runtime error: slice bounds out of range on `popTryFrame`

### ISSUE THREAD

**Issue by zyxkad** [dop251/goja#542]
## Problem

As my program running, this panic will happen randomly on any `goja.Object.Set`.

## Dependencies

```
	github.com/dop251/goja v0.0.0-20231014103939-873a1496dc8e
	github.com/dop251/goja_nodejs v0.0.0-20230914102007-198ba9a8b098
```

## Stacktrace

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 10 [running]:
github.com/dop251/goja.(*vm).popTryFrame(0x14000152b40?)
        /Users/ckpn/Mine/projects/golang/pkg/mod/github.com/dop251/goja@v0.0.0-20231014103939-873a1496dc8e/vm.go:721 +0x40
github.com/dop251/goja.(*vm).try(0x14000152b40, 0x140000bcd98)
        /Users/ckpn/Mine/projects/golang/pkg/mod/github.com/dop251/goja@v0.0.0-20231014103939-873a1496dc8e/vm.go:812 +0x204
github.com/dop251/goja.(*Runtime).try(...)
        /Users/ckpn/Mine/projects/golang/pkg/mod/github.com/dop251/goja@v0.0.0-20231014103939-873a1496dc8e/runtime.go:2522
github.com/dop251/goja.(*Object).Set(...)
        /Users/ckpn/Mine/projects/golang/pkg/mod/github.com/dop251/goja@v0.0.0-20231014103939-873a1496dc8e/value.go:880
github.com/kmcsr/go-liter/script.WrapPacketReader(0x1400011a060, 0x14000745800)
        /Users/ckpn/Mine/projects/golang/src/github.com/kmcsr/go-liter/script/packets.go:156 +0x810
github.com/kmcsr/go-liter/script.(*WrappedConn).Recv.func1(0x140001029c0?)
        /Users/ckpn/Mine/projects/golang/src/github.com/kmcsr/go-liter/script/conn.go:88 +0x30
github.com/kmcsr/go-liter/script.(*WrappedConn).Recv.(*EventLoop).RunOnLoop.func2()
        /Users/ckpn/Mine/projects/golang/pkg/mod/github.com/dop251/goja_nodejs@v0.0.0-20230914102007-198ba9a8b098/eventloop/eventloop.go:249 +0x30
github.com/dop251/goja_nodejs/eventloop.(*EventLoop).runAux(0x14000123080)
        /Users/ckpn/Mine/projects/golang/pkg/mod/github.com/dop251/goja_nodejs@v0.0.0-20230914102007-198ba9a8b098/eventloop/eventloop.go:258 +0x16c
github.com/dop251/goja_nodejs/eventloop.(*EventLoop).run(0x14000123080, 0x1)
        /Users/ckpn/Mine/projects/golang/pkg/mod/github.com/dop251/goja_nodejs@v0.0.0-20230914102007-198ba9a8b098/eventloop/eventloop.go:275 +0xbc
created by github.com/dop251/goja_nodejs/eventloop.(*EventLoop).Start in goroutine 1
        /Users/ckpn/Mine/projects/golang/pkg/mod/github.com/dop251/goja_nodejs@v0.0.0-20230914102007-198ba9a8b098/eventloop/eventloop.go:211 +0x60
exit status 2
```

## Relative function

<details>
<summary>WrapPacketReader</summary>

```go
func WrapPacketReader(p *liter.PacketReader, vm *goja.Runtime)(*WrappedPacketReader){
	EOF := vm.NewGoError(io.EOF)
	o := vm.NewObject()
	o.DefineAccessorProperty("protocol", vm.ToValue(func(goja.FunctionCall)(goja.Value){
		return vm.ToValue(p.Protocol())
	}), nil, goja.FLAG_FALSE, goja.FLAG_TRUE)
	o.DefineAccessorProperty("id", vm.ToValue(func(goja.FunctionCall)(goja.Value){
		return vm.ToValue((int)(p.Id()))
	}), nil, goja.FLAG_FALSE, goja.FLAG_TRUE)
	o.DefineAccessorProperty("offset", vm.ToValue(func(goja.FunctionCall)(goja.Value){
		return vm.ToValue(p.Offset())
	}), nil, goja.FLAG_FALSE, goja.FLAG_TRUE)
	o.DefineAccessorProperty("remain", vm.ToValue(func(goja.FunctionCall)(goja.Value){
		return vm.ToValue(p.Remain())
	}), nil, goja.FLAG_FALSE, goja.FLAG_TRUE)
	o.DefineAccessorProperty("data", vm.ToValue(func(goja.FunctionCall)(goja.Value){
		return vm.ToValue(vm.NewArrayBuffer(p.Bytes()))
	}), nil, goja.FLAG_FALSE, goja.FLAG_TRUE)
	o.Set("bytearray", func(call goja.FunctionCall)(goja.Value){
		buf := make([]byte, call.Arguments[0].ToInteger())
		if !p.ByteArray(buf) {
			panic(EOF)
		}
		return vm.ToValue(vm.NewArrayBuffer(buf))
	})
	o.Set("bool", func(call goja.FunctionCall)(goja.Value){
		v, ok := p.Bool()
		if !ok {
			panic(EOF)
		}
		return vm.ToValue(v)
	})
	o.Set("byte", func(call goja.FunctionCall)(goja.Value){
		v, ok := p.Byte()
		if !ok {
			panic(EOF)
		}
		return vm.ToValue(v)
	})
	o.Set("ubyte", func(call goja.FunctionCall)(goja.Value){
		v, ok := p.UByte()
		if !ok {
			panic(EOF)
		}
		return vm.ToValue(v)
	})
	o.Set("short", func(call goja.FunctionCall)(goja.Value){
		v, ok := p.Short()
		if !ok {
			panic(EOF)
		}
		return vm.ToValue(v)
	})
	o.Set("ushort", func(call goja.FunctionCall)(goja.Value){
		v, ok := p.UShort()
		if !ok {
			panic(EOF)
		}
		return vm.ToValue(v)
	})
	o.Set("int", func(call goja.FunctionCall)(goja.Value){
		v, ok := p.Int()
		if !ok {
			panic(EOF)
		}
		return vm.ToValue(v)
	})
	o.Set("long", func(call goja.FunctionCall)(goja.Value){
		v, ok := p.Long()
		if !ok {
			panic(EOF)
		}
		return vm.ToValue(v)
	})
	o.Set("varInt", func(call goja.FunctionCall)(goja.Value){
		v, ok := p.VarInt()
		if !ok {
			panic(EOF)
		}
		return vm.ToValue(v)
	})
	o.Set("varLong", func(call goja.FunctionCall)(goja.Value){
		v, ok := p.VarLong()
		if !ok {
			panic(EOF)
		}
		return vm.ToValue(v)
	})
	o.Set("float", func(call goja.FunctionCall)(goja.Value){
		v, ok := p.Float()
		if !ok {
			panic(EOF)
		}
		return vm.ToValue(v)
	})
	o.Set("double", func(call goja.FunctionCall)(goja.Value){
		v, ok := p.Double()
		if !ok {
			panic(EOF)
		}
		return vm.ToValue(v)
	})
	o.Set("string", func(call goja.FunctionCall)(goja.Value){
		v, ok := p.String()
		if !ok {
			panic(EOF)
		}
		return vm.ToValue(v)
	})
	o.Set("uuid", func(call goja.FunctionCall)(goja.Value){
		id, ok := p.UUID()
		if !ok {
			panic(EOF)
		}
		return vm.ToValue(id.String())
	})
	o.Set("json", func(call goja.FunctionCall)(goja.Value){
		var v any
		if err := p.JSON(&v); err != nil {
			panic(vm.NewGoError(err))
		}
		return vm.ToValue(v)
	})
	return &WrappedPacketReader{
		PacketReader: p,
		exports: o,
	}
}
```

</details>

**Comment by zyxkad** [comment]
I'm pretty sure I didn't use the runtime concurrently, but if you have any other questions about my full codes, you can visit <https://github.com/kmcsr/go-liter/tree/master/script>

**Comment by dop251** [comment]
Errors like this are almost always caused by data races. Bear in mind that you cannot use any Object created within the loop outside the loop as this also may use the vm.

I suggest you to try the following: write a test case that fails and run it with the race detector, most likely this will reveal the problem.

**Comment by zyxkad** [comment]
OH, ok, I see why it panics now:
```go
	o.Set("send", func(call goja.FunctionCall)(goja.Value){
		if sent {
			panic(vm.ToValue("This packet is already being sent"))
		}
		sent = true
		pm, r, e := vm.NewPromise()
		go func(){
			if err := conn.Send(p); err != nil {
				e(err)
			}else{
				r(goja.Undefined())
			}
		}()
		return vm.ToValue(pm)
	})
```

I was trying to resolve promise concurrency
