### ISSUE TITLE
sourcemap: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by fullheart** [dop251/goja#550]
# Problem

I'm working on a TS project with [k6](https://k6.io/) tests, which are compiled with Vite (Babel and Rollup) in JavaScript. The sourcemap support works fine, except for this file: [k6-jslib-aws-y_ANwLL3.cjs.zip](https://github.com/dop251/goja/files/13987972/k6-jslib-aws-y_ANwLL3.cjs.zip) (the sourcemap is embedded as the last line of the file)

A thrown JS error cause this Go runtime error:
```
ERRO[0000] unexpected k6 panic: runtime error: index out of range [-1]
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
go.k6.io/k6/cmd.(*rootCommand).execute.func2()
        go.k6.io/k6@v0.46.0/cmd/root.go:96 +0x69
panic({0x1690780, 0xc0000463d8})
        runtime/panic.go:884 +0x213
github.com/go-sourcemap/sourcemap.(*Consumer).source(0xc00096bc40?, 0xc0003a3760, 0x5, 0x19)
        github.com/go-sourcemap/sourcemap@v2.1.4-0.20211119122758-180fcef48034+incompatible/consumer.go:199 +0x1d8
github.com/go-sourcemap/sourcemap.(*Consumer).Source(0xc0009eb200?, 0xc00096bce0?, 0xc00004ebd0?)
        github.com/go-sourcemap/sourcemap@v2.1.4-0.20211119122758-180fcef48034+incompatible/consumer.go:178 +0x6d
github.com/dop251/goja/file.(*File).Position(0xc000132600, 0xd2)
        github.com/dop251/goja@v0.0.0-20230919151941-fc55792775de/file/file.go:161 +0x1c5
github.com/dop251/goja.(*StackFrame).Position(0xc00096bdb0)
        github.com/dop251/goja@v0.0.0-20230919151941-fc55792775de/runtime.go:228 +0x4b
github.com/dop251/goja.(*StackFrame).Write(0xc00096bdb0, 0x176830c?)
        github.com/dop251/goja@v0.0.0-20230919151941-fc55792775de/runtime.go:271 +0x76
github.com/dop251/goja.(*Exception).writeFullStack(0xc00096bdf8?, 0xc00010e4e0?)
        github.com/dop251/goja@v0.0.0-20230919151941-fc55792775de/runtime.go:363 +0x7e
github.com/dop251/goja.(*Exception).String(0xc0009f1530?)
        github.com/dop251/goja@v0.0.0-20230919151941-fc55792775de/runtime.go:384 +0x85
go.k6.io/k6/js.(*scriptException).StackTrace(0x1ac7b00?)
        go.k6.io/k6@v0.46.0/js/runner.go:915 +0x1c
go.k6.io/k6/cmd.(*rootCommand).execute(0xc0004f7d40)
        go.k6.io/k6@v0.46.0/cmd/root.go:118 +0x1f5
go.k6.io/k6/cmd.Execute()
        go.k6.io/k6@v0.46.0/cmd/root.go:137 +0x31
main.main()
        k6/main.go:12 +0x17 
```

# Expected behaviour
Interestingly, the runtime error only occurs once when I repeat the execution in quick sequence. The other executions show the correct JS error:

```
ERRO[0000] Error: invalid AWS access key ID; reason: size should be between 16 and 128 characters, got 5
        at file:///node_modules/k6-jslib-aws/src/internal/config.ts:94:22(57)
        at createAwsConfig (file:///src/utils/utils.ts:22:6(34))
        at file:///src/writing-fixed-requests-per-minute.ts:11:19(22)
        at go.k6.io/k6/js.(*requireImpl).require-fm (native)
        at file:///dist/writing-spike-users.cjs:5:27(26)  hint="script exception"
```

**Comment by codebien** [comment]
Hey @fullheart,
k6 maintainer here, as it sounds more like a k6 issue than a `goja` one, can you open an issue directly to the [k6 repo](https://github.com/grafana/k6/issues), please? Then I will directly look into it.

**Comment by fullheart** [comment]
Hey @codebien, 
great thank you for your fast feedback. I created a new issue in the k6 repo: https://github.com/grafana/k6/issues/3556
Thank you for checking it. I close this issue now.
